name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ec2-user@your-ec2-ip:/var/www/html/

      - name: Restart Web Server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip 'sudo systemctl restart apache2'

