name: Deploy to Home Server

on:
  push:
    branches:
      - TEST

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_2 }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no -i ~/hserv.pem ./* roguh@10.12.1.61:/var/www/html
